2024-04-12 10:21:24,671 DEBUG: Combined data: [] [in generate_embeddings.py:19]
2024-04-12 10:21:24,758 DEBUG: Embedding generation completed [in generate_embeddings.py:25]
2024-04-12 10:21:24,758 INFO: Generated 0 embeddings to insert into PGVector: Casino [in generate_embeddings.py:26]
2024-04-12 10:21:24,760 INFO: Embeddings added to the database [in generate_embeddings.py:31]
2024-04-12 10:21:24,760 INFO: Generated embeddings for (0, <langchain_community.vectorstores.pgvector.PGVector object at 0x1af5c1050>) items of type url [in process_data.py:96]
2024-04-12 10:21:24,763 ERROR: Exception on /api/process-data/url [POST] [in app.py:828]
Traceback (most recent call last):
  File "/Users/chriswest/Desktop/new_project/.venv/lib/python3.11/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/new_project/.venv/lib/python3.11/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/new_project/.venv/lib/python3.11/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chriswest/Desktop/new_project/.venv/lib/python3.11/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for '/process-data.process_url' did not return a valid response. The function either returned None or ended without a return statement.
2024-04-12 13:31:03,786 INFO: PGVector extension enabled successfully. [in helper_functions.py:191]
